from PyQt5 import QtCore, QtGui, QtWidgets
from sympy import *
from styles import stylesheets
class Ui_Form(object):
        def setupUi(self, Form):
                Form.setObjectName("Form")
                Form.resize(1043, 834)
                Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
                Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
                self.frame = QtWidgets.QFrame(Form)
                self.frame.setGeometry(QtCore.QRect(320, 40, 401, 701))
                self.frame.setStyleSheet("border-image: url(Phone.png);")
                self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame.setObjectName("frame")
                self.pushButton_1 = QtWidgets.QPushButton(Form)
                self.pushButton_1.setGeometry(QtCore.QRect(370, 480, 31, 31))
                font = QtGui.QFont()
                font.setPointSize(8)
                font.setBold(True)
                font.setWeight(75)
                self.lineEdit = QtWidgets.QLineEdit(Form)
                self.lineEdit.setGeometry(QtCore.QRect(360, 140, 321, 101))
                self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
                self.lineEdit.setStyleSheet("background-color: #292929;\n"
        "color:white")
                self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
                self.lineEdit.setObjectName("lineEdit")
                self.pushButton_1.setFont(font)
                self.pushButton_1.setStyleSheet(stylesheets.stylePushbuttondarkblue(self))
                self.pushButton_1.setObjectName("pushButton")
                self.pushButton_1.clicked.connect(lambda:self.lineEdit.insert('1'))

                self.pushButton_2 = QtWidgets.QPushButton(Form)
                self.pushButton_2.setGeometry(QtCore.QRect(420, 480, 31, 31))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_2.setFont(font)
                self.pushButton_2.setStyleSheet(stylesheets.stylePushbuttondarkblue(self))
                self.pushButton_2.setObjectName("pushButton_2")
                self.pushButton_2.clicked.connect(lambda:self.lineEdit.insert('2'))

                self.pushButton_3 = QtWidgets.QPushButton(Form)
                self.pushButton_3.setGeometry(QtCore.QRect(470, 480, 31, 31))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_3.setFont(font)
                self.pushButton_3.setStyleSheet(stylesheets.stylePushbuttondarkblue(self))
                self.pushButton_3.setObjectName("pushButton_3")
                self.pushButton_3.clicked.connect(lambda:self.lineEdit.insert('3'))

                self.pushButton_4 = QtWidgets.QPushButton(Form)
                self.pushButton_4.setGeometry(QtCore.QRect(370, 520, 31, 31))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_4.setFont(font)
                self.pushButton_4.setStyleSheet(stylesheets.stylePushbuttondarkblue(self))
                self.pushButton_4.setObjectName("pushButton_4")
                self.pushButton_4.clicked.connect(lambda:self.lineEdit.insert('4'))

                self.pushButton_5 = QtWidgets.QPushButton(Form)
                self.pushButton_5.setGeometry(QtCore.QRect(420, 520, 31, 31))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_5.setFont(font)
                self.pushButton_5.setStyleSheet(stylesheets.stylePushbuttondarkblue(self))
                self.pushButton_5.setObjectName("pushButton_5")
                self.pushButton_5.clicked.connect(lambda:self.lineEdit.insert('5'))

                self.pushButton_6 = QtWidgets.QPushButton(Form)
                self.pushButton_6.setGeometry(QtCore.QRect(470, 520, 31, 31))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_6.setFont(font)
                self.pushButton_6.setStyleSheet(stylesheets.stylePushbuttondarkblue(self))
                self.pushButton_6.setObjectName("pushButton_9")
                self.pushButton_6.clicked.connect(lambda:self.lineEdit.insert('6'))

                self.pushButton_7 = QtWidgets.QPushButton(Form)
                self.pushButton_7.setGeometry(QtCore.QRect(370, 560, 31, 31))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_7.setFont(font)
                self.pushButton_7.setStyleSheet(stylesheets.stylePushbuttondarkblue(self))
                self.pushButton_7.setObjectName("pushButton_6")
                self.pushButton_7.clicked.connect(lambda:self.lineEdit.insert('7'))

                self.pushButton_8 = QtWidgets.QPushButton(Form)
                self.pushButton_8.setGeometry(QtCore.QRect(420, 560, 31, 31))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_8.setFont(font)
                self.pushButton_8.setStyleSheet(stylesheets.stylePushbuttondarkblue(self))
                self.pushButton_8.setObjectName("pushButton_7")
                self.pushButton_8.clicked.connect(lambda:self.lineEdit.insert('8'))

                self.pushButton_9 = QtWidgets.QPushButton(Form)
                self.pushButton_9.setGeometry(QtCore.QRect(470, 560, 31, 31))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_9.setFont(font)
                self.pushButton_9.setStyleSheet(stylesheets.stylePushbuttondarkblue(self))
                self.pushButton_9.setObjectName("pushButton_8")
                self.pushButton_9.clicked.connect(lambda:self.lineEdit.insert('9'))

                self.pushButton_0 = QtWidgets.QPushButton(Form)
                self.pushButton_0.setGeometry(QtCore.QRect(370, 600, 31, 31))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_0.setFont(font)
                self.pushButton_0.setStyleSheet(stylesheets.stylePushbuttondarkblue(self))
                self.pushButton_0.setObjectName("pushButton_10")
                self.pushButton_0.clicked.connect(lambda:self.lineEdit.insert('0'))

                self.pushButton_dot = QtWidgets.QPushButton(Form)
                self.pushButton_dot.setGeometry(QtCore.QRect(420, 600, 31, 31))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_dot.setFont(font)
                self.pushButton_dot.setStyleSheet(stylesheets.stylePushbuttondarkblue(self))
                self.pushButton_dot.setObjectName("pushButton_11")
                self.pushButton_dot.clicked.connect(lambda:self.lineEdit.insert('.'))

                self.pushButton_del = QtWidgets.QPushButton(Form)
                self.pushButton_del.setGeometry(QtCore.QRect(470, 600, 31, 31))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_del.setFont(font)
                self.pushButton_del.setStyleSheet(stylesheets.stylePushbuttondarkblue(self))
                self.pushButton_del.setObjectName("pushButton_12")
                self.pushButton_del.clicked.connect(lambda:self.delete())

                self.pushButton_plus = QtWidgets.QPushButton(Form)
                self.pushButton_plus.setGeometry(QtCore.QRect(560, 520, 41, 71))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_plus.setFont(font)
                self.pushButton_plus.setStyleSheet(stylesheets.stylePushbuttongrey(self))
                self.pushButton_plus.setObjectName("pushButton_13")
                self.pushButton_plus.clicked.connect(lambda:self.lineEdit.insert('+'))

                self.pushButton_Math = QtWidgets.QPushButton(Form)
                self.pushButton_Math.setGeometry(QtCore.QRect(560, 600, 91, 31))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_Math.setFont(font)
                self.pushButton_Math.setStyleSheet(stylesheets.stylesPushbuttonpurple(self))
                self.pushButton_Math.setObjectName("pushButton_14")
                self.pushButton_Math.clicked.connect(lambda:self.MathBrain())

                self.pushButton_minus = QtWidgets.QPushButton(Form)
                self.pushButton_minus.setGeometry(QtCore.QRect(560, 480, 41, 31))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_minus.setFont(font)
                self.pushButton_minus.setStyleSheet(stylesheets.stylePushbuttongrey(self))
                self.pushButton_minus.setObjectName("pushButton_15")
                self.pushButton_minus.clicked.connect(lambda:self.lineEdit.insert('-'))

                self.pushButton_divide = QtWidgets.QPushButton(Form)
                self.pushButton_divide.setGeometry(QtCore.QRect(610, 560, 41, 31))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_divide.setFont(font)
                self.pushButton_divide.setStyleSheet(stylesheets.stylePushbuttongrey(self))
                self.pushButton_divide.setObjectName("pushButton_16")
                self.pushButton_divide.clicked.connect(lambda:self.lineEdit.insert('/'))

                self.pushButton_multi = QtWidgets.QPushButton(Form)
                self.pushButton_multi.setGeometry(QtCore.QRect(610, 520, 41, 31))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_multi.setFont(font)
                self.pushButton_multi.setStyleSheet(stylesheets.stylePushbuttongrey(self))
                self.pushButton_multi.setObjectName("pushButton_17")
                self.pushButton_multi.clicked.connect(lambda:self.lineEdit.insert('*'))

                self.pushButton_lbracket = QtWidgets.QPushButton(Form)
                self.pushButton_lbracket.setGeometry(QtCore.QRect(370, 430, 61, 31))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_lbracket.setFont(font)
                self.pushButton_lbracket.setStyleSheet(stylesheets.stylePushbuttongrey(self))
                self.pushButton_lbracket.setObjectName("pushButton_18")
                self.pushButton_lbracket.clicked.connect(lambda:self.lineEdit.insert('('))

                self.pushButton_rbracket = QtWidgets.QPushButton(Form)
                self.pushButton_rbracket.setGeometry(QtCore.QRect(440, 430, 61, 31))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_rbracket.setFont(font)
                self.pushButton_rbracket.setStyleSheet(stylesheets.stylePushbuttongrey(self))
                self.pushButton_rbracket.setObjectName("pushButton_19")
                self.pushButton_rbracket.clicked.connect(lambda:self.lineEdit.insert(')'))

                self.pushButton_clear = QtWidgets.QPushButton(Form)
                self.pushButton_clear.setGeometry(QtCore.QRect(560, 430, 41, 31))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_clear.setFont(font)
                self.pushButton_clear.setStyleSheet(stylesheets.stylePushbuttondarkblue(self))
                self.pushButton_clear.setObjectName("pushButton_20")
                self.pushButton_clear.clicked.connect(self.lineEdit.clear)

                self.pushButton_music = QtWidgets.QPushButton(Form)
                self.pushButton_music.setGeometry(QtCore.QRect(610, 430, 41, 31))
                font = QtGui.QFont()
                font.setFamily("font bottons music pro")
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_music.setFont(font)
                self.pushButton_music.setStyleSheet(stylesheets.stylePushbuttondarkblue(self))
                self.pushButton_music.setObjectName("pushButton_21")
                self.pushButton_music.clicked.connect(lambda:self.OpenMusic())

                self.pushButton_x = QtWidgets.QPushButton(Form)
                self.pushButton_x.setGeometry(QtCore.QRect(610, 480, 41, 31))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_x.setFont(font)
                self.pushButton_x.setStyleSheet(stylesheets.stylesPushbuttonorange(self))
                self.pushButton_x.setObjectName("pushButton_22")
                self.pushButton_x.clicked.connect(lambda:self.lineEdit.insert('x'))

                self.pushButton_integrate = QtWidgets.QPushButton(Form)
                self.pushButton_integrate.setGeometry(QtCore.QRect(360, 370, 141, 31))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_integrate.setFont(font)
                self.pushButton_integrate.setStyleSheet(stylesheets.stylesPushbuttonorange(self))
                self.pushButton_integrate.setObjectName("pushButton_23")
                self.pushButton_integrate.clicked.connect(lambda:self.lineEdit.insert("integrate()"))

                self.pushButton_diff = QtWidgets.QPushButton(Form)
                self.pushButton_diff.setGeometry(QtCore.QRect(540, 370, 141, 31))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_diff.setFont(font)
                self.pushButton_diff.setStyleSheet(stylesheets.stylesPushbuttonorange(self))
                self.pushButton_diff.setObjectName("pushButton_24")
                self.pushButton_diff.clicked.connect(lambda:self.lineEdit.insert("diff()"))

                self.label = QtWidgets.QLabel(Form)
                self.label.setGeometry(QtCore.QRect(360, 300, 321, 41))
                self.label.setStyleSheet("color:#bdc3c3;")
                self.label.setAlignment(QtCore.Qt.AlignCenter)
                self.label.setObjectName("label")

                self.pushButton_closeapp = QtWidgets.QPushButton(Form)
                self.pushButton_closeapp.setGeometry(QtCore.QRect(490, 670, 61, 61))
                self.pushButton_closeapp.setStyleSheet(stylesheets.stylesPushbuttoncloseapp(self))
                self.pushButton_closeapp.setText("")
                self.pushButton_closeapp.setObjectName("pushButton_25")
                self.pushButton_closeapp.clicked.connect(lambda:sys.exit())

                self.label_2 = QtWidgets.QLabel(Form)
                self.label_2.setGeometry(QtCore.QRect(350, 634, 351, 21))
                self.label_2.setStyleSheet("color:#bdc3c3;")
                self.label_2.setAlignment(QtCore.Qt.AlignCenter)
                self.label_2.setObjectName("label_2")

                self.textBrowser = QtWidgets.QTextBrowser(Form)
                self.textBrowser.setGeometry(QtCore.QRect(360, 250, 321, 51))
                self.textBrowser.setStyleSheet("background-color: #292929;\n"
        "color:white")
                self.textBrowser.setObjectName("textBrowser") 

                self.retranslateUi(Form)
                QtCore.QMetaObject.connectSlotsByName(Form)

        def retranslateUi(self, Form):
                _translate = QtCore.QCoreApplication.translate
                Form.setWindowTitle(_translate("Form", "Form"))
                self.pushButton_1.setText(_translate("Form", "1"))
                self.pushButton_2.setText(_translate("Form", "2"))
                self.pushButton_3.setText(_translate("Form", "3"))
                self.pushButton_4.setText(_translate("Form", "4"))
                self.pushButton_5.setText(_translate("Form", "5"))
                self.pushButton_6.setText(_translate("Form", "6"))
                self.pushButton_7.setText(_translate("Form", "7"))
                self.pushButton_8.setText(_translate("Form", "8"))
                self.pushButton_9.setText(_translate("Form", "9"))
                self.pushButton_0.setText(_translate("Form", "0"))
                self.pushButton_dot.setText(_translate("Form", "."))
                self.pushButton_del.setText(_translate("Form", "C"))
                self.pushButton_plus.setText(_translate("Form", "+"))
                self.pushButton_Math.setText(_translate("Form", "="))
                self.pushButton_minus.setText(_translate("Form", "-"))
                self.pushButton_divide.setText(_translate("Form", "÷"))
                self.pushButton_multi.setText(_translate("Form", "×"))
                self.pushButton_lbracket.setText(_translate("Form", "("))
                self.pushButton_rbracket.setText(_translate("Form", ")"))
                self.pushButton_clear.setText(_translate("Form", "AC"))
                self.pushButton_music.setText(_translate("Form", "a"))
                self.pushButton_x.setText(_translate("Form", "X"))
                self.pushButton_integrate.setText(_translate("Form", "Integral"))
                self.pushButton_diff.setText(_translate("Form", "Derivative"))
                self.label.setText(_translate("Form", "Easy-to-use integral and derivative calculator with audio playback"))
                self.label_2.setText(_translate("Form", "All right reserved. Jakub Kiełb 2022 ©"))
                self.lineEdit.setPlaceholderText(_translate("Form", "E.G log(x)+sin(x)+5*cos(2*x)+6*x"))
                self.textBrowser.setPlaceholderText(_translate("Form", "Output"))
        def MathBrain(self):
                import scipy.integrate
                from sympy import sin, cos,tan,sqrt, Function, diff, sqrt,log, pi ,acos ,asin ,atan,symbols
                from math import e
                x=symbols('x')
                line=self.lineEdit.text()
                if line=="":
                        self.textBrowser.setText("Enter a mathematical expression")
                else:
                        try:
                                DoMath=eval(line)
                                self.textBrowser.setText(str(DoMath))
                        except ZeroDivisionError:
                                self.textBrowser.setText("Don't divide by zero!")

        def OpenMusic(self):
                import winsound
                winsound.PlaySound(r'Song1.wav', winsound.SND_ASYNC)
        def delete(self):
                line=self.lineEdit.text()
                LineList=list(line)
                LineList=LineList[:-1]
                self.lineEdit.setText(''.join(map(str, LineList)))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())