class stylesheets(object):
    def stylePushbuttondarkblue(self):
        return("QPushButton{\n"
"border-radius:15px;\n"
"background-color: rgb(85, 85, 127);\n"
"color:white;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color:rgb(170, 170, 255);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color:rgb(85, 85, 255);\n"
"}")
    def stylePushbuttongrey(self):
        return("QPushButton{\n"
"border-radius:15px;\n"
"background-color:#bdc3c3;\n"
"color:white;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color:#5c5c5c;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color:#343434;\n"
"}")
    def stylesPushbuttonpurple(self):
        return("QPushButton{\n"
"border-radius:15px;\n"
"background-color: rgb(85, 0, 255);\n"
"color:white;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color:rgb(170, 85, 255);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color:rgb(85, 85, 255);\n"
"}")
    def stylesPushbuttonorange(self):
        return("QPushButton{\n"
"border-radius:15px;\n"
"background-color:rgb(255, 170, 127);\n"
"color:white;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color:rgb(255, 85, 0);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color:rgb(255, 0, 0);\n"
"}")
    def stylesPushbuttoncloseapp(self):
        return("QPushButton{\n"
"border-radius:30px;\n"
"background-color:white;\n"
"border: 3px solid grey;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border: 4px solid grey;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"border: 5px solid grey;\n"
"}\n"
"")